name: Test

on:
  pull_request:
    branches: ["main", "release", "testing"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v2

      - name: use node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: test project
        run: |
          npm install
          npm run test:prod
