name: Build & Lint

on: [push, pull_request]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v2

      - name: use node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: build project
        run: |
          npm install
          npm run build:prod

      - name: lint project
        run: npm run lint
